### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by BentBr** [doofinder/php-doofinder#101]
Hey Folks,

We have a frequent error when using your search client.

**What we are doing:**
```
$searchParams = [
    'hashid'    => $this->engine,
    'indices'   => [$this->index],
    'query'     => $searchKeyword,
    'rpp'       => 100
];
$dfClient->search($searchParams);
```
The searchKeyword is a sanitized user input.

**The error in Search/Client, Line 177:**
`$this->_lastPage = ceil($total / $rpp); // Division by zero error`

It looks like your client does not want to handle zero results when querying your API.
Furthermore, I'm confused why your documentation said we can give a rpp, but it's immediately overwritten here.

Any ideas how to handle that? :)
Here's a link to our issue in sentry.io:
[Isses's link](https://sentry.io/share/issue/e080a614f5ec40d19a2fc171d0ac622a/)

Best,
Bent

**Comment by silviaherguedas** [comment]
Hello,
I see that you are using the old version, so I recommend you to update your API to [new version](https://github.com/doofinder/php-doofinder/blob/master/src/Search/README_SEARCH.md). 
Since no changes will be made for the old version.
Thanks

**Comment by BentBr** [comment]
Thx for the hint - wasn't aware of that.

Best,
Bent
