### ISSUE TITLE
Wrong response when you delete a datatype and re-create it

### ISSUE THREAD

**Issue by carlosescri** [doofinder/php-doofinder#22]
> During the catalogsearch_fulltext reindex following API calls are performed:
>
> `DELETE https://eu1-api.doofinder.com/v1/{hashid}/types/{datatype}`
> `POST https://eu1-api.doofinder.com/v1/{hashid}/types`
>
> The second request fails with an unhandled error "Bad request", it should be some named error which can be catched, not a "Bad request", like: "IndexingInProgress" or "ThrottledResponse".
> 
> Preconditions:
> - sample data must be installed and indexed

**Comment by carlosescri** [comment]
This comment is from our Magento 2 devs.

**Comment by carlosescri** [comment]
More feedback:

> Here https://github.com/doofinder/php-doofinder/blob/master/src/Management/Errors/Utils.php we would expect that when indexing is in progress an IndexingInProgress error would be thrown, but this does not happen:
> 
> [2017-12-06 08:22:04] main.CRITICAL: The client made a bad request: {"message": "There is an indexing operation in progress.Please try again later", "error_code": "INDEX_IN_PROGRESS"} {"exception":"[object] (Doofinder\\Api\\Management\\Errors\\BadRequest(code: 0): The client made a bad request: {\"message\": \"There is an indexing operation in progress.Please try again later\", \"error_code\": \"INDEX_IN_PROGRESS\"} at /var/www/magento/vendor/doofinder/doofinder/src/Management/Errors/Utils.php:41)"} []
> 
> This occurs due the unhandled BadRequest error, this is not a bad request, this error should not occur, request is fine, simply api is not ready to handle our request,so we should receive IndexingInProgress or some other specific error. This is misleading and extremely difficult to handle correctly. We recall that it did not work like that before, especially that we strictly implemented some precautions exactly for this issue - index is not ready due the asyncrounous type deletion. If module doesn't get an IndexingInProgress error, it won't wait until indexing finishes.
>
> Did you change something in the API which was not included in PHP library? It had worked before, something must have changed and it seems it wasn't M2 module.

**Comment by JoeZ99** [comment]
Turns out the API already has a response for that and it's a `Conflict` error response , and the php library is already ready for that. just had to raise that error in case of datatype crud during indexing.
