### ISSUE TITLE
(1) Modify autoload.php to register Management libraries

### ISSUE THREAD

**Issue by mingoarte** [doofinder/php-doofinder#51]
If a client don't want to use composer, our client won't work. We have to modify our autoload.php to register management libraries.

**Comment by albertodoofinder** [comment]
Related support ticket https://doofinder.freshdesk.com/a/tickets/36059

**Comment by mingoarte** [comment]
Related to: https://doofinder.freshdesk.com/a/tickets/36059

**Comment by mingoarte** [comment]
The user has to put folder attached within his project and reference the autoload.php file to load all the classes and packages. The folder is generated with composer, if he does not want to use our vendor folder, he can follow this: https://github.com/doofinder/php-doofinder/blob/master/src/Management/README_MANAGEMENT.md#composer and generate his own vendor.
[vendor.zip](https://github.com/doofinder/php-doofinder/files/5218282/vendor.zip)
