### ISSUE TITLE
(1) getSearchEngines() issue

### ISSUE THREAD

**Issue by albertodoofinder** [doofinder/php-doofinder#55]
Customer using v5 of https://github.com/doofinder/php-doofinder reports that cannot index through API. It is getting timeout/status 0 when calling getSearchEngines()

Affected account: isabelle.quivaux@betafence.com

Affected search engine: 47652605f1a06acb9bb5e597d26db100

Related support ticket https://doofinder.freshdesk.com/a/tickets/40247

**Comment by mingoarte** [comment]
@albertodoofinder 

I've tested the `getSearchEngines()` call and everything works fine. Here is how I've test it:

```php
<?php
require_once(__DIR__ . '/autoload.php');


define('API_KEY', 'eu1-5ebc80ed9e74fbed16b9fad2ccb6c15e4043d785');

// Instantiate the object, use your Doofinder's API_KEY.
$client = new \Doofinder\Api\Management\Client(API_KEY);

// Create a search engine
$SearchEngines = $client->getSearchEngines();

print_r($SearchEngines);
```

I will answer to the client to request more information.
