### ISSUE TITLE
Let the client library exceptions be easily classified

### ISSUE THREAD

**Issue by JoeZ99** [doofinder/php-doofinder#6]
Currently, the php exception that is thrown when the query limit is reached is:

``` php
throw new DoofinderException("Requests Limit Reached");
```

if an user wants to know what to do when the request limit is reached, she has to parse the exception message . It would be easier if:
- there's a specific exception for that case    or
- the generic exception has some code

**Comment by carlosescri** [comment]
The Walking Dead...
