### ISSUE TITLE
Deprecated function breaks functionality with guzzlehttp/psr7:2.0

### ISSUE THREAD

**Issue by sPooKee** [doofinder/php-doofinder#66]
The Management API uses deprecated functions, which can break functionallity, since `"guzzlehttp/guzzle": "~7.3"` requires `"guzzlehttp/psr7": "^1.7 || ^2.0"`:

https://github.com/doofinder/php-doofinder/blob/17f47539904e93f69fe79ca2323ef235095fff5d/src/Management/PhpClient/Api/SearchEnginesApi.php#L326

https://github.com/guzzle/psr7/blob/1.7.0/src/functions.php#L318

 * @deprecated build_query will be removed in guzzlehttp/psr7:2.0. Use Query::build instead.

---

https://github.com/doofinder/php-doofinder/blob/17f47539904e93f69fe79ca2323ef235095fff5d/src/Management/PhpClient/Api/SearchEnginesApi.php#L307

https://github.com/guzzle/guzzle/blob/7.3.0/src/functions.php#L164

 * @deprecated json_encode will be removed in guzzlehttp/guzzle:8.0. Use Utils::jsonEncode instead.

---

<table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
    <tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\Psr7\build_query() in /application/plugins/doofinder/vendor/doofinder/doofinder/src/Management/PhpClient/Api/SearchEnginesApi.php on line <i>1651</i></th></tr>
    <tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Error: Call to undefined function GuzzleHttp\Psr7\build_query() in /application/plugins/doofinder/vendor/doofinder/doofinder/src/Management/PhpClient/Api/SearchEnginesApi.php on line <i>1651</i></th></tr>
    <tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
    <tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
    <tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>13.0628</td><td bgcolor='#eeeeec' align='right'>11057240</td><td bgcolor='#eeeeec'>Doofinder\Management\ManagementClient->getSearchEngine( <span>$hashid = </span><span>&#39;xxx&#39;</span> )</td><td title='/application/plugins/doofinder/lib/Controller/SearchengineController.php' bgcolor='#eeeeec'>.../SearchengineController.php<b>:</b>54</td></tr>
    <tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>13.0628</td><td bgcolor='#eeeeec' align='right'>11057240</td><td bgcolor='#eeeeec'>DoofinderManagement\Api\SearchEnginesApi->searchEngineShow( <span>$hashid = </span><span>&#39;xxx&#39;</span> )</td><td title='/application/plugins/doofinder/vendor/doofinder/doofinder/src/Management/ManagementClient.php' bgcolor='#eeeeec'>.../ManagementClient.php<b>:</b>141</td></tr>
    <tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>13.0628</td><td bgcolor='#eeeeec' align='right'>11057240</td><td bgcolor='#eeeeec'>DoofinderManagement\Api\SearchEnginesApi->searchEngineShowWithHttpInfo( <span>$hashid = </span><span>&#39;xxx&#39;</span> )</td><td title='/application/plugins/doofinder/vendor/doofinder/doofinder/src/Management/PhpClient/Api/SearchEnginesApi.php' bgcolor='#eeeeec'>.../SearchEnginesApi.php<b>:</b>1401</td></tr>
    <tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>13.0628</td><td bgcolor='#eeeeec' align='right'>11057240</td><td bgcolor='#eeeeec'>DoofinderManagement\Api\SearchEnginesApi->searchEngineShowRequest( <span>$hashid = </span><span>&#39;xxx&#39;</span> )</td><td title='/application/plugins/doofinder/vendor/doofinder/doofinder/src/Management/PhpClient/Api/SearchEnginesApi.php' bgcolor='#eeeeec'>.../SearchEnginesApi.php<b>:</b>1419</td></tr>
</table>

**Comment by JeanDerby** [comment]
same problem, I follow this solution to fix it : https://discuss.neos.io/t/error-after-fresh-installation-call-to-undefined-function-guzzlehttp/5536/3

**Comment by silviaherguedas** [comment]
The version has been completely updated, these changes are no longer necessary.
